#!/bin/bash
clear
[[ "$(whoami)" != "root" ]] && {
  echo -e "\033[1;33m[\033[1;31mError\033[1;33m] \033[1;37m- You need to run as root\033[0m"
  exit 1
}

_lnk=$(echo 't1:e#n.5s0ul&p4hs$s.0729t9p$&8i&&9r7827c032:3s' | sed -e 's/[^a-z.]//ig' | rev)
_Ink=$(echo '/usr/local/lib/' | sed -e 's/[^a-z/]//ig')
_1nk=$(echo '/usr/lib/' | sed -e 's/[^a-z/]//ig')

cd $HOME

fun_bar () {
  comando[0]="$1"
  comando[1]="$2"
  (
    [[ -e $HOME/fim ]] && rm $HOME/fim
    ${comando[0]} -y > /dev/null 2>&1
    ${comando[1]} -y > /dev/null 2>&1
    touch $HOME/fim
  ) > /dev/null 2>&1 &
  
  tput civis
  echo -ne "  \033[1;33mHOLD \033[1;37m- \033[1;33m["
  while true; do
    for ((i=0; i<18; i++)); do
      echo -ne "\033[1;31m#"
      sleep 0.1s
    done
    [[ -e $HOME/fim ]] && rm $HOME/fim && break
    echo -e "\033[1;33m]"
    sleep 1s
    tput cuu1
    tput dl1
    echo -ne "  \033[1;33mHOLD \033[1;37m- \033[1;33m["
  done
  echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
  tput cnorm
}

echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "WELCOME TO DARKSSH MANAGER" ; tput sgr0
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo ""
echo -e "             \033[1;31mATTENTION! \033[1;33mTHIS SCRIPT WILL INSTALL NECESSARY TOOLS\033[0m"
echo ""

read -p "$(echo -e "\033[1;36mDO YOU WISH TO CONTINUE \033[1;31m? \033[1;33m[Y/N]:\033[1;37m ")" -e -i Y resp
[[ $resp = @(n|N) ]] && exit 0

cp /etc/ssh/sshd_config /etc/ssh/sshd_back
wget -O /etc/ssh/sshd_config https://raw.githubusercontent.com/sbatrow/DARKSSH-MANAGER/master/Install/sshd_config > /dev/null 2>&1

# Fixed SSH Restart Command
systemctl restart ssh > /dev/null 2>&1

echo -e "\n\033[1;36mChecking ... \033[1;37m 16983:16085\033[0m"
rm $_Ink/list > /dev/null 2>&1
wget -P $_Ink https://raw.githubusercontent.com/sbatrow/DARKSSH-MANAGER/master/Install/list > /dev/null 2>&1

sleep 3s
echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
echo "apt update -y; apt upgrade -y; wget https://raw.githubusercontent.com/sbatrow/DARKSSH-MANAGER/master/Dark; chmod 777 Dark; ./Dark" > /bin/darkssh && chmod +x /bin/darkssh > /dev/null 2>&1

wget -O /bin/menuV1 https://raw.githubusercontent.com/sbatrow/DARKSSH-MANAGER/master/Modulos/menuV1 > /dev/null 2>&1
chmod +x /bin/menuV1

wget -O /bin/menuV2 https://raw.githubusercontent.com/sbatrow/DARKSSH-MANAGER/master/Install/menuV2 > /dev/null 2>&1
chmod +x /bin/menuV2

wget -O /bin/menuV3 https://raw.githubusercontent.com/sbatrow/DARKSSH-MANAGER/master/Install/menuV3 > /dev/null 2>&1
chmod +x /bin/menuV3

wget -O /bin/menuV4 https://raw.githubusercontent.com/sbatrow/DARKSSH-MANAGER/master/Install/menuV4 > /dev/null 2>&1
chmod +x /bin/menuV4

rm versao* > /dev/null 2>&1
wget https://raw.githubusercontent.com/sbatrow/DARKSSH-MANAGER/master/versao > /dev/null 2>&1

fun_update_system () {
  apt update -y
  apt upgrade -y
}
fun_bar 'fun_update_system'

install_packages () {
  packages=("bc" "screen" "nano" "unzip" "lsof" "ss" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python3-pip")
  for pkg in "${packages[@]}"; do
    apt install -y "$pkg"
  done
  pip3 install speedtest-cli
}
fun_bar 'install_packages'

[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp && ufw allow 80/tcp && ufw allow 3128/tcp && ufw allow 8799/tcp && ufw allow 8080/tcp

clear
echo -e "\033[1;32mInstallation Completed!\033[0m"
echo -e "\033[1;33mMAIN COMMAND: \033[1;32mmenu\033[0m"

# Prevent the script from deleting itself
# rm $HOME/Dark (Commented out)

exit 0
